Drop schema if exists public cascade; 
create schema public;
drop schema if exists ghalog cascade;  
create schema ghalog;
drop schema if exists ghaconf cascade; 
create schema ghaconf;
drop schema if exists ghamsg cascade;  
create schema ghamsg;
drop schema if exists log cascade;  
create schema log;
drop schema if exists conf cascade; 
create schema conf;
drop schema if exists msg cascade;  
create schema msg;
